version: '3.7'
services:
  ua-service:
    build:
      context: .
    image: ungewoehnlicher-aufenthaltsort:latest
    depends_on:
      - database
    networks:
      - public
      - backend
      - fae-message-broker_backend

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=ungewoehnlicher-aufenthaltsort
    networks:
      - backend

  proxy:
    image: dockercloud/haproxy
    links:
      - ua-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - public

networks:
  public:
    driver: bridge
  backend:
    driver: bridge
  fae-message-broker_backend:
    external: true
