version: '3'
services:
  ungewoehnlicher-aufenthaltsort:
    container_name: ungewoehnlicher-aufenthaltsort
    build:
      context: .
    image: ungewoehnlicher-aufenthaltsort:latest
    depends_on:
      - postgres
    ports:
      - 45222
    environment:
     - SERVICE_PORTS=45222
    deploy:
        replicas: 2
    networks:
      - fae-ua
      - fae-message-broker_backend

  postgres:
    container_name: ungewoehnlicher-aufenthaltsort-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=ungewoehnlicher-aufenthaltsort
    networks:
      - fae-ua

  proxy:
    container_name: ungewoehnlicher-aufenthaltsort-proxy
    image: dockercloud/haproxy
    depends_on:
      - ungewoehnlicher-aufenthaltsort
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    deploy:
        placement:
            constraints: [node.role == manager]
    networks:
      - fae-ua
     
networks:
  fae-ua:
    driver: overlay
  fae-message-broker_backend:
    external: true
