version: '3'
services:
  web:
    build: .
    depends_on:
      - postgres
    expose:
      - 80
    networks:
      - fae-message-broker_backend

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=ort
    networks:
      - fae-message-broker_backend

  proxy:
    image: dockercloud/haproxy:1.6.7
    ports:
      - 8081:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fae-message-broker_backend

networks:
  fae-message-broker_backend:
    external: true
